############################
############################
## Compile GitHub Actions ##
############################
############################
name: Create PDFs

#
# Documentation:
# https://github.com/marketplace/actions/github-action-for-latex
# https://tex-d-l.llstserv.dfn.narkive.com/KsPxiTk5/insdljs-sty-not-found
# http://www.math.uakron.edu/~dpstory/webeq.html
#
# Commit pdfs
# https://github.com/marketplace/actions/github-action-for-latex
#

################################
# Start the job on push to dev #
################################
on:
  pull_request_review:
    branches:
      - dev
    types: [submitted]

###############
# Set the Job #
###############
jobs:
  build_latex:
    if: github.event.review.state == 'approved'
    # Name the Job
    name: Compile PDFs
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      ##########################
      # Download extra package #
      ##########################
      - name: Download the insdljs package as a zip
        run: wget http://www.math.uakron.edu/~dpstory/acrotex/acrotex.zip -O ./acrotex.zip
      - name: Unzip package
        run: unzip acrotex.zip
      ####################
      # Run the compiler #
      ####################
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "src/*.tex"
          glob_root_file: true
          pre_compile: "tex acrotex/acrotex.ins"
        env:
          TEXINPUTS: ".:./acrotex//:"
      ###################
      # Push pdf commit #
      ###################
      - name: Move pdfs
        env:
          FILES: ./*.pdf
        run: |
          chmod +x ./.github/workflows/move-changed-files.sh
          ./.github/workflows/move-changed-files.sh
        # mv connectfour.pdf pdf/connectfour.pdf
      - name: Commit compiled pdfs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated commit: Add compiled pdfs"
          file_pattern: pdf/*.pdf
      ########################
      # Merge to all_commits #
      ########################
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: ${{ github.head_ref }}
          target: 'all_commits'
